name: 4640docker

on:
  push:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          file: frontend/Dockerfile
          push: true
          tags: agraystone/4640frontend:latest
      -
        name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          file: backend/Dockerfile
          push: true
          tags: agraystone/4640backend:latest
